services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx-prod
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/certbot:/var/certbot
    depends_on:
      - ticketo
    networks:
      - vps_infra

  ticketo:
    build:
      context: ../../app
      dockerfile: Dockerfile
    container_name: ticketo-app-prod
    environment:
      DB_USERNAME: "${APP_DB_USERNAME}"
      DB_PASSWORD: "${APP_DB_PASSWORD}"
      DB_URL: "jdbc:mysql://db:3306/${APP_DB_NAME}"
      PORT: "${APP_PORT}"
      EMAIL: "${APP_EMAIL}"
      APP_PASSWORD: "${APP_APP_PASSWORD}"
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - vps_infra

  db:
    image: mysql:8.0
    container_name: ticketo-db-prod
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_MYSQL_ROOT_PASSWORD}"
    restart: unless-stopped
    volumes:
      - ticketo_db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - vps_infra

volumes:
  ticketo_db_data:

networks:
  vps_infra:
