server {
    listen 80;
    server_name ticketo.me;

    location /.well-known/acme-challenge/ {
        root /var/certbot;
        allow all;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name ticketo.me;

    ssl_certificate /etc/letsencrypt/live/ticketo.me/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ticketo.me/privkey.pem;

    # Proxy para el servicio
    location / {
        # Pasar la solicitud al contenedor de Ticketo
        proxy_pass http://ticketo:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
