server {
    listen 80;
    server_name www.ticketo.me;

    location /.well-known/acme-challenge/ {
        root /var/certbot;
        allow all;
    }

    location / {
        return 301 https://ticketo.me$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name www.ticketo.me;

    ssl_certificate /etc/letsencrypt/live/www.ticketo.me/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/www.ticketo.me/privkey.pem;

    location / {
        return 301 https://ticketo.me$request_uri;
    }
}
